CREATE TABLE events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    description TEXT,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE event_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id),
    date DATE NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    capacity INTEGER NOT NULL,
    registration_open BOOLEAN NOT NULL,
    status VARCHAR(30) NOT NULL
);

CREATE TABLE registrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES events(id),
    event_session_id BIGINT NOT NULL REFERENCES event_sessions(id),
    full_name VARCHAR(150) NOT NULL,
    email VARCHAR(180) NOT NULL,
    cpf VARCHAR(11) NOT NULL,
    phone VARCHAR(20) NOT NULL,
    registration_type VARCHAR(20) NOT NULL,
    service_area VARCHAR(80),
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_registration_event_cpf UNIQUE (event_id, cpf)
);

CREATE INDEX idx_registration_cpf ON registrations(cpf);
CREATE INDEX idx_registration_full_name ON registrations(full_name);

CREATE TABLE tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id BIGINT NOT NULL UNIQUE REFERENCES registrations(id),
    qr_token VARCHAR(36) NOT NULL,
    issued_at TIMESTAMP NOT NULL,
    status VARCHAR(30) NOT NULL,
    CONSTRAINT uk_ticket_qr_token UNIQUE (qr_token)
);

CREATE INDEX idx_ticket_qr_token ON tickets(qr_token);

CREATE TABLE check_ins (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration_id BIGINT NOT NULL UNIQUE REFERENCES registrations(id),
    checked_in_at TIMESTAMP NOT NULL,
    operator_id BIGINT,
    device_identifier VARCHAR(120),
    CONSTRAINT uk_checkin_registration UNIQUE (registration_id)
);
