ALTER TABLE event_sessions
    ADD CONSTRAINT uk_event_sessions_id_event
        UNIQUE (id, event_id);

CREATE TABLE participants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    event_id BIGINT NOT NULL,

    event_session_id BIGINT,

    full_name VARCHAR(150) NOT NULL,

    email VARCHAR(180),

    phone VARCHAR(20) NOT NULL,

    source VARCHAR(30) NOT NULL,

    status VARCHAR(30) NOT NULL,

    notes TEXT,

    active BOOLEAN NOT NULL DEFAULT TRUE,

    version BIGINT NOT NULL DEFAULT 0,

    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_participants_event
        FOREIGN KEY (event_id)
        REFERENCES events(id),

    CONSTRAINT fk_participants_session_event
        FOREIGN KEY (event_session_id, event_id)
        REFERENCES event_sessions(id, event_id),

    CONSTRAINT ck_participants_full_name_not_blank
        CHECK (char_length(trim(full_name)) > 0),

    CONSTRAINT ck_participants_phone_not_blank
        CHECK (char_length(trim(phone)) > 0),

    CONSTRAINT ck_participants_source
        CHECK (
            source IN (
                'MANUAL',
                'SYMPLA',
                'IMPORT'
            )
        ),

    CONSTRAINT ck_participants_status
        CHECK (
            status IN (
                'REGISTERED',
                'CONFIRMED',
                'CANCELLED',
                'NO_SHOW'
            )
        )
);

CREATE INDEX idx_participants_event_id
    ON participants(event_id);

CREATE INDEX idx_participants_event_session_id
    ON participants(event_session_id);

CREATE INDEX idx_participants_full_name
    ON participants(full_name);

CREATE INDEX idx_participants_phone
    ON participants(phone);

CREATE INDEX idx_participants_status
    ON participants(status);

CREATE INDEX idx_participants_active
    ON participants(active);