ALTER TABLE participants
    ALTER COLUMN phone DROP NOT NULL;

CREATE TABLE participant_integrations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    participant_id BIGINT NOT NULL,

    provider VARCHAR(30) NOT NULL,

    external_participant_id VARCHAR(120) NOT NULL,

    external_ticket_id VARCHAR(120),

    external_order_id VARCHAR(120),

    ticket_status VARCHAR(40),

    order_status VARCHAR(40),

    checked_in BOOLEAN NOT NULL DEFAULT FALSE,

    external_updated_at TIMESTAMP,

    last_sync_at TIMESTAMP NOT NULL,

    created_at TIMESTAMP NOT NULL,

    updated_at TIMESTAMP NOT NULL,

    version BIGINT NOT NULL DEFAULT 0,

    CONSTRAINT fk_participant_integrations_participant
        FOREIGN KEY (participant_id)
        REFERENCES participants(id),

    CONSTRAINT ck_participant_integrations_provider
        CHECK (
            provider IN (
                'SYMPLA',
                'PAGTICKETS',
                'EVENTBRITE',
                'OTHER'
            )
        ),

    CONSTRAINT uk_participant_integrations_provider_external_participant
        UNIQUE (
            provider,
            external_participant_id
        ),

    CONSTRAINT uk_participant_integrations_provider_external_ticket
        UNIQUE (
            provider,
            external_ticket_id
        )
);

CREATE INDEX idx_participant_integrations_participant_id
    ON participant_integrations(participant_id);

CREATE INDEX idx_participant_integrations_provider
    ON participant_integrations(provider);

CREATE INDEX idx_participant_integrations_external_order_id
    ON participant_integrations(
        provider,
        external_order_id
    );

CREATE INDEX idx_participant_integrations_last_sync_at
    ON participant_integrations(last_sync_at);